version: "3.3"

services:
  client:
    stdin_open: true
    tty: true
    restart: always

    build: ./

    volumes:
      - .:/client/

    ports:
      - 5000:5000

    networks:
      - dockernet

networks:
  dockernet:
      external: true